# Dataset : https://www.kaggle.com/datasets/oktayrdeki/houses-in-london

# Q1 
* ## Load the Data
* ## Display the First 5 Entries
* ## Display the Last 5 Entries
* ## View Dataset Information
* ## Generate Descriptive Statistics (Numeric and Categorical Data)

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("Real-Estate-House-Analysis-Project\Data Set\london_houses.csv")

In [3]:
df.head()

,Address,Neighborhood,Bedrooms,Bathrooms,Square Meters,Building Age,Garden,Garage,Floors,Property Type,Heating Type,Balcony,Interior Style,View,Materials,Building Status,Price (£)
0,78 Regent Street,Notting Hill,2,3,179,72,No,No,3,Semi-Detached,Electric Heating,High-level Balcony,Industrial,Garden,Marble,Renovated,2291200
1,198 Oxford Street,Westminster,2,1,123,34,Yes,No,1,Apartment,Central Heating,High-level Balcony,Industrial,City,Laminate Flooring,Old,1476000
2,18 Regent Street,Soho,5,3,168,38,No,Yes,3,Semi-Detached,Central Heating,No Balcony,Industrial,Street,Wood,Renovated,1881600
3,39 Piccadilly Circus,Islington,5,1,237,53,Yes,Yes,1,Apartment,Underfloor Heating,No Balcony,Classic,Park,Granite,Renovated,1896000
4,116 Fleet Street,Marylebone,4,1,127,23,No,Yes,2,Semi-Detached,Central Heating,No Balcony,Modern,Park,Wood,Old,1524000

In [4]:
df.tail()

,Address,Neighborhood,Bedrooms,Bathrooms,Square Meters,Building Age,Garden,Garage,Floors,Property Type,Heating Type,Balcony,Interior Style,View,Materials,Building Status,Price (£)
995,44 Camden High Street,Westminster,1,3,81,4,Yes,Yes,2,Semi-Detached,Central Heating,Low-level Balcony,Modern,Street,Laminate Flooring,Renovated,1166400
996,165 Park Lane,Camden,1,1,65,51,No,No,1,Apartment,Underfloor Heating,No Balcony,Industrial,Garden,Wood,Old,563333
997,99 Camden High Street,Camden,4,1,191,27,No,Yes,2,Semi-Detached,Central Heating,Low-level Balcony,Minimalist,Park,Laminate Flooring,Old,1986399
998,155 Park Lane,Camden,5,2,131,3,Yes,No,2,Detached House,Underfloor Heating,High-level Balcony,Modern,Park,Laminate Flooring,Renovated,1703000
999,145 Baker Street,Kensington,4,2,185,53,No,No,1,Apartment,Electric Heating,No Balcony,Modern,Street,Wood,Old,2343333

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Address          1000 non-null   str
 1   Neighborhood     1000 non-null   str
 2   Bedrooms         1000 non-null   int64
 3   Bathrooms        1000 non-null   int64
 4   Square Meters    1000 non-null   int64
 5   Building Age     1000 non-null   int64
 6   Garden           1000 non-null   str
 7   Garage           1000 non-null   str
 8   Floors           1000 non-null   int64
 9   Property Type    1000 non-null   str
 10  Heating Type     1000 non-null   str
 11  Balcony          1000 non-null   str
 12  Interior Style   1000 non-null   str
 13  View             1000 non-null   str
 14  Materials        1000 non-null   str
 15  Building Status  1000 non-null   str
 16  Price (£)        1000 non-null   int64
dtypes: int64(6), str(11)
memory usage: 132.9 KB

In [6]:
df.describe()

,Bedrooms,Bathrooms,Square Meters,Building Age,Floors,Price (£)
count,1000.000000,1000.000000,1000.0000,1000.00000,1000.000000,1.000000e+03
mean,3.013000,2.003000,149.6270,49.96500,1.991000,1.840807e+06
std,1.393834,0.808483,58.0562,29.07086,0.821946,8.793484e+05
min,1.000000,1.000000,50.0000,1.00000,1.000000,3.866660e+05
25%,2.000000,1.000000,99.0000,24.00000,1.000000,1.161400e+06
50%,3.000000,2.000000,148.0000,50.00000,2.000000,1.721999e+06
75%,4.000000,3.000000,201.0000,76.00000,3.000000,2.390500e+06
max,5.000000,3.000000,249.0000,99.00000,3.000000,4.980000e+06

# Q2
* ## Check and Resolve Duplicate Entries
* ## Check and Handle Missing Values

In [7]:
df.drop_duplicates(inplace=True)

In [8]:
df.fillna(0, inplace=True)

,Address,Neighborhood,Bedrooms,Bathrooms,Square Meters,Building Age,Garden,Garage,Floors,Property Type,Heating Type,Balcony,Interior Style,View,Materials,Building Status,Price (£)
0,78 Regent Street,Notting Hill,2,3,179,72,No,No,3,Semi-Detached,Electric Heating,High-level Balcony,Industrial,Garden,Marble,Renovated,2291200
1,198 Oxford Street,Westminster,2,1,123,34,Yes,No,1,Apartment,Central Heating,High-level Balcony,Industrial,City,Laminate Flooring,Old,1476000
2,18 Regent Street,Soho,5,3,168,38,No,Yes,3,Semi-Detached,Central Heating,No Balcony,Industrial,Street,Wood,Renovated,1881600
3,39 Piccadilly Circus,Islington,5,1,237,53,Yes,Yes,1,Apartment,Underfloor Heating,No Balcony,Classic,Park,Granite,Renovated,1896000
4,116 Fleet Street,Marylebone,4,1,127,23,No,Yes,2,Semi-Detached,Central Heating,No Balcony,Modern,Park,Wood,Old,1524000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,44 Camden High Street,Westminster,1,3,81,4,Yes,Yes,2,Semi-Detached,Central Heating,Low-level Balcony,Modern,Street,Laminate Flooring,Renovated,1166400
996,165 Park Lane,Camden,1,1,65,51,No,No,1,Apartment,Underfloor Heating,No Balcony,Industrial,Garden,Wood,Old,563333
997,99 Camden High Street,Camden,4,1,191,27,No,Yes,2,Semi-Detached,Central Heating,Low-level Balcony,Minimalist,Park,Laminate Flooring,Old,1986399
998,155 Park Lane,Camden,5,2,131,3,Yes,No,2,Detached House,Underfloor Heating,High-level Balcony,Modern,Park,Laminate Flooring,Renovated,1703000
999,145 Baker Street,Kensington,4,2,185,53,No,No,1,Apartment,Electric Heating,No Balcony,Modern,Street,Wood,Old,2343333

# Q3
* ## Using aggregate function to calculate (Max, Min, Mean) of sales column

In [9]:
max_price = df["Price (£)"].max()
min_price = df["Price (£)"].min()
mean_price = df["Price (£)"].mean()
max_price, min_price, mean_price

(np.int64(4980000), np.int64(386666), np.float64(1840807.278))

# Q4
* ## Generate a column that specifies the price per square meter (.2F).
* ## Generte a column that specifies the total rooms in house

In [11]:
df['Price_per_sqm'] = df['Price (£)'] / df['Square Meters']
df.head()

,Address,Neighborhood,Bedrooms,Bathrooms,Square Meters,Building Age,Garden,Garage,Floors,Property Type,Heating Type,Balcony,Interior Style,View,Materials,Building Status,Price (£),Price_per_sqm
0,78 Regent Street,Notting Hill,2,3,179,72,No,No,3,Semi-Detached,Electric Heating,High-level Balcony,Industrial,Garden,Marble,Renovated,2291200,12800.0
1,198 Oxford Street,Westminster,2,1,123,34,Yes,No,1,Apartment,Central Heating,High-level Balcony,Industrial,City,Laminate Flooring,Old,1476000,12000.0
2,18 Regent Street,Soho,5,3,168,38,No,Yes,3,Semi-Detached,Central Heating,No Balcony,Industrial,Street,Wood,Renovated,1881600,11200.0
3,39 Piccadilly Circus,Islington,5,1,237,53,Yes,Yes,1,Apartment,Underfloor Heating,No Balcony,Classic,Park,Granite,Renovated,1896000,8000.0
4,116 Fleet Street,Marylebone,4,1,127,23,No,Yes,2,Semi-Detached,Central Heating,No Balcony,Modern,Park,Wood,Old,1524000,12000.0

In [12]:
df['Total_Rooms'] = df['Bedrooms'] + df['Bathrooms']
df.head()

,Address,Neighborhood,Bedrooms,Bathrooms,Square Meters,Building Age,Garden,Garage,Floors,Property Type,Heating Type,Balcony,Interior Style,View,Materials,Building Status,Price (£),Price_per_sqm,Total_Rooms
0,78 Regent Street,Notting Hill,2,3,179,72,No,No,3,Semi-Detached,Electric Heating,High-level Balcony,Industrial,Garden,Marble,Renovated,2291200,12800.0,5
1,198 Oxford Street,Westminster,2,1,123,34,Yes,No,1,Apartment,Central Heating,High-level Balcony,Industrial,City,Laminate Flooring,Old,1476000,12000.0,3
2,18 Regent Street,Soho,5,3,168,38,No,Yes,3,Semi-Detached,Central Heating,No Balcony,Industrial,Street,Wood,Renovated,1881600,11200.0,8
3,39 Piccadilly Circus,Islington,5,1,237,53,Yes,Yes,1,Apartment,Underfloor Heating,No Balcony,Classic,Park,Granite,Renovated,1896000,8000.0,6
4,116 Fleet Street,Marylebone,4,1,127,23,No,Yes,2,Semi-Detached,Central Heating,No Balcony,Modern,Park,Wood,Old,1524000,12000.0,5

# Q5
* ## What is the oldest house and price of it ?
* ## What is the newest house and price of it ?
### note(If there is more than one, calculate their mean.)

In [17]:
max_age = df['Building Age'].max()
oldest_houses = df[df['Building Age'] == max_age]
oldest_houses

,Address,Neighborhood,Bedrooms,Bathrooms,Square Meters,Building Age,Garden,Garage,Floors,Property Type,Heating Type,Balcony,Interior Style,View,Materials,Building Status,Price (£),Price_per_sqm,Total_Rooms
139,87 Regent Street,Shoreditch,5,3,94,99,No,Yes,2,Semi-Detached,Gas Heating,High-level Balcony,Minimalist,Garden,Marble,Old,827199,8799.989362,8
184,109 Strand,Notting Hill,1,2,60,99,Yes,Yes,3,Semi-Detached,Central Heating,High-level Balcony,Modern,Garden,Laminate Flooring,Renovated,768000,12800.000000,3
273,96 King's Road,Westminster,4,1,246,99,No,No,2,Apartment,Electric Heating,High-level Balcony,Minimalist,Garden,Marble,New,2952000,12000.000000,5
422,184 Park Lane,Chelsea,5,2,120,99,No,Yes,1,Semi-Detached,Central Heating,High-level Balcony,Modern,Garden,Wood,Renovated,1920000,16000.000000,7
536,8 Park Lane,Islington,3,1,104,99,Yes,No,2,Semi-Detached,Underfloor Heating,No Balcony,Industrial,City,Wood,Old,998400,9600.000000,4
673,83 King's Road,Notting Hill,2,2,170,99,No,Yes,2,Apartment,Electric Heating,No Balcony,Minimalist,Street,Granite,New,1813333,10666.664706,4
702,108 Park Lane,Chelsea,4,1,54,99,Yes,Yes,3,Detached House,Underfloor Heating,High-level Balcony,Minimalist,Garden,Laminate Flooring,Old,1080000,20000.000000,5
993,176 Camden High Street,Camden,2,1,80,99,Yes,No,1,Detached House,Gas Heating,Low-level Balcony,Classic,Garden,Laminate Flooring,New,1039999,12999.987500,3

In [18]:
mean_price_oldest = oldest_houses['Price (£)'].mean()
mean_price_oldest

np.float64(1424866.375)

In [19]:
min_age = df['Building Age'].min()
newest_houses = df[df['Building Age'] == min_age]
newest_houses

,Address,Neighborhood,Bedrooms,Bathrooms,Square Meters,Building Age,Garden,Garage,Floors,Property Type,Heating Type,Balcony,Interior Style,View,Materials,Building Status,Price (£),Price_per_sqm,Total_Rooms
12,139 Fleet Street,Kensington,5,1,171,1,Yes,No,2,Semi-Detached,Gas Heating,Low-level Balcony,Classic,City,Wood,New,2599200,15200.000000,6
62,89 Regent Street,Chelsea,4,2,86,1,No,No,3,Apartment,Gas Heating,High-level Balcony,Classic,Street,Wood,Renovated,1146666,13333.325581,6
204,157 Fleet Street,Notting Hill,4,1,77,1,No,Yes,3,Apartment,Underfloor Heating,No Balcony,Modern,Garden,Laminate Flooring,Old,821333,10666.662338,5
358,83 Fleet Street,Notting Hill,3,2,153,1,Yes,Yes,3,Detached House,Electric Heating,No Balcony,Industrial,Park,Laminate Flooring,New,2448000,16000.000000,5
411,163 Strand,Soho,2,3,172,1,Yes,No,2,Apartment,Underfloor Heating,High-level Balcony,Minimalist,Street,Granite,Renovated,1605333,9333.331395,5

In [20]:
mean_price_newest = newest_houses['Price (£)'].mean()
mean_price_newest

np.float64(1724106.4)

# Q6
* ## Transform : (Garden , Garage) to numeric by mapping

#### note:(Yes = 1 / No = 0)

In [21]:
mapping = {'Yes': 1, 'No': 0}
df['Garden'] = df['Garden'].map(mapping)
df['Garage'] = df['Garage'].map(mapping)
df.head()

,Address,Neighborhood,Bedrooms,Bathrooms,Square Meters,Building Age,Garden,Garage,Floors,Property Type,Heating Type,Balcony,Interior Style,View,Materials,Building Status,Price (£),Price_per_sqm,Total_Rooms
0,78 Regent Street,Notting Hill,2,3,179,72,0,0,3,Semi-Detached,Electric Heating,High-level Balcony,Industrial,Garden,Marble,Renovated,2291200,12800.0,5
1,198 Oxford Street,Westminster,2,1,123,34,1,0,1,Apartment,Central Heating,High-level Balcony,Industrial,City,Laminate Flooring,Old,1476000,12000.0,3
2,18 Regent Street,Soho,5,3,168,38,0,1,3,Semi-Detached,Central Heating,No Balcony,Industrial,Street,Wood,Renovated,1881600,11200.0,8
3,39 Piccadilly Circus,Islington,5,1,237,53,1,1,1,Apartment,Underfloor Heating,No Balcony,Classic,Park,Granite,Renovated,1896000,8000.0,6
4,116 Fleet Street,Marylebone,4,1,127,23,0,1,2,Semi-Detached,Central Heating,No Balcony,Modern,Park,Wood,Old,1524000,12000.0,5

# Q7
* ## Generate pivot tables for indexing by the following categories: (Neighborhood, Property Type, Heating Type, Balcony, View, Materials, and Building Status). The values will represent the mean price for each category.

* ## save each of them in a separate sheet within an Excel file

In [22]:
categories = ['Neighborhood', 'Property Type', 'Heating Type', 'Balcony', 'View', 'Materials', 'Building Status']
with pd.ExcelWriter('Houses_Analysis.xlsx') as writer:
    for cat in categories:
        pivot = df.pivot_table(index=cat, values='Price (£)', aggfunc='mean')
        pivot.to_excel(writer, sheet_name=cat)